#%RAML 1.0
version: v1
baseUri: https://mocksvc.mulesoft.com/mocks/510e2a51-a820-4bc2-ab2b-fe54380c55b9 # 
title: br-sys-api


traits: 
  credential: 
    headers: 
      client_id:
        type: string
      client_secret:
        type: string
        required: true
 
  





/brget:
  get:
    queryParameters: 
      order_no:
        required: true
        type: number
    responses: 
        200:
          body: 
            application/json:
              example: !include responsebrorder.json
  post:
    body: 
      application/json:
        type: !include dataType.raml
        example: !include responsebrorder.json
    responses: 
      200:  
        body: 
          application/json:
            example: !include responsebrpost.json